#include "Portable/DarkRelicRules.h"
#include "Portable/BellkeeperAttack.h"
#include "Portable/FuryAura.h"
#include <cstdlib>
#include <iostream>
#include <limits>

using namespace dark_relic;
int checks = 0;
void check(bool condition, const char* message) {
    ++checks;
    if (!condition) { std::cerr << "FAIL: " << message << '\n'; std::exit(1); }
}
void win(Rules& game) {
    check(game.zone(true), "enter zone");
    check(game.extract(), "begin extraction");
    check(game.tick(20), "advance countdown");
    check(game.snapshot().phase == Phase::Escaped, "escaped");
}
int main() {
    check(fury_aura(6,6,true)==0, "aura starts from zero");
    check(fury_aura(5.75,6,true)==1, "aura ramps up in quarter second");
    check(fury_aura(3,6,true)==1, "aura remains full through power plateau");
    check(fury_aura(1,6,true)==0.5, "aura halfway faded in final second");
    check(fury_aura(0,6,true)==0 && fury_aura(-1,6,true)==0, "expired aura stays off");
    check(fury_aura(3,6,false)==0, "death and extraction results extinguish aura");
    check(fury_aura(7,6,true)==0 && fury_aura(1,0,true)==0, "invalid timers cannot glow");
    check(fury_aura(std::numeric_limits<double>::quiet_NaN(),6,true)==0, "nonfinite aura fails closed");
    double prior=1;
    for (int i=200;i>=0;--i) {
        const double intensity=fury_aura(i/100.0,6,true);
        if (intensity>prior || intensity<0 || intensity>1) check(false,"fade is monotonic and bounded");
        prior=intensity;
    }
    check(prior==0,"fade reaches exact zero");
    Rules w;
    check(!w.act(Action::RelicBurst) && !w.act(Action::Rally), "abilities rejected before run");
    check(w.start() && w.act(Action::Light), "start sword chain");
    check(w.snapshot().combo_step==1 && w.snapshot().attack_damage==25, "first strike keeps existing damage");
    check(!w.act(Action::Light) && w.snapshot().combo_step==1, "spam cannot advance combo during recovery");
    check(w.tick(0.5) && w.act(Action::Light) && w.snapshot().combo_step==2, "second timed strike");
    check(w.tick(0.5) && w.act(Action::Light), "third timed strike accepted");
    check(w.snapshot().finisher && w.snapshot().attack_damage==50 && w.snapshot().action_remaining==0.7, "third strike becomes stronger finisher");
    check(w.snapshot().stamina==70, "combo charges 15 15 20 with time regeneration");
    check(w.tick(0.7) && w.act(Action::Light) && w.snapshot().combo_step==1 && !w.snapshot().finisher, "fourth strike starts fresh chain");
    check(w.tick(1.3) && w.snapshot().combo_step==0 && w.act(Action::Light) && w.snapshot().combo_step==1, "expired combo restarts at one");
    check(w.tick(0.5) && w.act(Action::Heavy) && w.snapshot().combo_step==0 && w.snapshot().attack_damage==55, "heavy retains damage and cancels chain");
    check(w.tick(2) && w.act(Action::Rally), "fury activates after recovery");
    check(w.snapshot().rally_remaining==6 && w.snapshot().rally_cooldown==20, "fury has bounded duration and cooldown");
    check(w.damage(20) && w.snapshot().health==85, "fury reduces real incoming damage by quarter");
    check(w.tick(0.35) && !w.act(Action::Rally), "fury cannot stack or refresh");
    check(w.act(Action::RelicBurst) && std::abs(w.snapshot().attack_damage-60.75)<1e-8, "fury amplifies relic magic");
    check(w.snapshot().burst_cooldown==8 && w.snapshot().combo_step==0, "burst starts cooldown and breaks chain");
    check(w.tick(0.8) && !w.act(Action::RelicBurst), "burst cooldown survives recovery");
    check(w.tick(4.85) && w.snapshot().rally_remaining==0, "fury expires exactly including partitioned deltas");
    check(w.damage(20) && w.snapshot().health==65, "normal damage restored at expiry");
    check(w.act(Action::Light) && w.snapshot().attack_damage==25, "normal offense restored after fury");
    check(w.tick(3) && w.act(Action::RelicBurst), "burst becomes usable after cooldown");
    check(w.damage(1000) && w.snapshot().rally_remaining==0 && w.snapshot().burst_cooldown==0 && w.snapshot().attack_damage==0, "death clears all transient abilities");
    check(w.start() && w.snapshot().combo_step==0 && w.act(Action::Rally), "restart resets abilities");
    check(w.tick(0.35) && w.act(Action::Dodge) && !w.damage(20), "dodge remains invulnerable during fury");
    check(w.snapshot().combo_step==0, "dodge cancels sword chain");
    Rules poor;
    Tuning poor_t; poor_t.stamina_regen=0;
    check(poor.configure(poor_t) && poor.start(), "stamina boundary fixture");
    for(int i=0;i<3;++i) check(poor.act(Action::Heavy) && poor.tick(1), "drain ability stamina fixture");
    check(!poor.act(Action::RelicBurst) && !poor.act(Action::Rally) && poor.snapshot().stamina==10 && poor.snapshot().burst_cooldown==0 && poor.snapshot().rally_cooldown==0, "failed ability costs and cooldowns atomic");
    Rules exact;
    Tuning exact_t; exact_t.stamina=35; exact_t.stamina_regen=0;
    check(exact.configure(exact_t) && exact.start() && exact.act(Action::RelicBurst) && exact.snapshot().stamina==0, "burst accepts exact cost");
    check(exact.tick(8) && !exact.act(Action::RelicBurst), "cooldown expiry cannot bypass exhausted stamina");
    Rules tune_w;
    Tuning wt; wt.rally_damage_taken=0;
    check(!tune_w.configure(wt), "fury cannot be configured for invulnerability");
    wt=Tuning{}; wt.rally_duration=wt.rally_cooldown;
    check(!tune_w.configure(wt), "reject permanently refreshable fury");
    wt=Tuning{}; wt.burst_damage=std::numeric_limits<double>::quiet_NaN();
    check(!tune_w.configure(wt), "reject invalid ability damage");
    wt=Tuning{}; wt.rally_damage_multiplier=4;
    check(!tune_w.configure(wt), "reject excessive fury multiplier");
    Rules clock_a, clock_b;
    clock_a.start(); clock_b.start(); clock_a.act(Action::Rally); clock_b.act(Action::Rally);
    clock_a.tick(20); for(int i=0;i<200;++i) clock_b.tick(0.1);
    check(clock_a.snapshot().rally_cooldown==clock_b.snapshot().rally_cooldown && clock_b.snapshot().rally_remaining==0, "ability clocks independent of frame partition");
    Rules leave;
    Tuning lt; lt.extraction_seconds=1;
    leave.configure(lt); leave.start(); leave.act(Action::Rally); leave.zone(true); leave.extract(); leave.tick(1);
    check(leave.snapshot().phase==Phase::Escaped && leave.snapshot().rally_remaining==0 && leave.snapshot().rally_cooldown==0, "extraction ends fury immediately");
    check(!leave.act(Action::Rally) && !leave.act(Action::RelicBurst), "cannot cast after escape");
    Rules legacy;
    Bank legacy_bank; legacy_bank.credits=123; legacy_bank.items[0]=2;
    check(legacy.load(legacy_bank) && legacy.start() && legacy.snapshot().bank.credits==123 && legacy.snapshot().burst_cooldown==0, "existing version-one bank loads without ability migration");
    BellkeeperAttack boss;
    check(!boss.begin(), "boss waits for initial cooldown");
    check(!boss.update_health(75,150), "boss not enraged at exactly half");
    check(!boss.update_health(0,150), "dead boss cannot enter enrage");
    check(!boss.tick(3) && boss.begin(), "boss starts area windup after cooldown");
    check(!boss.tick(1.59), "boss never hits before telegraph completes");
    check(boss.tick(0.02) && !boss.tick(0.1), "boss resolves once even with overshoot");
    check(!boss.begin(), "boss has post-area cooldown");
    check(boss.hits(360,180,true), "boss radius and height boundaries inclusive");
    check(!boss.hits(361,0,true) && !boss.hits(200,181,true), "outside area and height safe");
    check(!boss.hits(200,0,false), "cover blocks area damage");
    check(!boss.hits(std::numeric_limits<double>::quiet_NaN(),0,true), "invalid area distance rejected");
    check(boss.update_health(74,150) && !boss.update_health(70,150), "enrage triggers once below half");
    boss.tick(7);
    check(boss.begin() && boss.duration>=1.25 && boss.damage()==34, "enrage keeps readable warning and tuned damage");
    check(!boss.tick(-1) && !boss.tick(std::numeric_limits<double>::quiet_NaN()), "invalid boss delta rejected");
    boss.cancel();
    check(!boss.tick(2) && boss.remaining==0, "death cancellation cannot resolve pending area");
    Rules g;
    check(!g.extract(), "cannot extract before run");
    check(!g.pickup(Item::Iron, 1, 1), "no loot before run");
    check(g.start(), "start");
    check(!g.start(), "cannot reset active run");
    check(!g.extract(), "requires presence");
    check(g.pickup(Item::Iron, 2, 1), "iron pickup");
    check(!g.pickup(Item::Iron, 2, 1), "repeated overlap rejected");
    check(g.pickup(Item::Blackbell, 1, 2), "relic pickup");
    check(!g.pickup(Item::Blackbell, 1, 3), "one relic per run");
    check(!g.pickup(static_cast<Item>(255), 1, 4), "invalid item");
    check(!g.pickup(Item::Salt, -1, 5), "negative pickup");
    check(!g.pickup(Item::Salt, 1, 0), "zero identity rejected");
    check(g.zone(true) && g.extract(), "countdown starts");
    check(g.tick(19), "partial countdown");
    check(!g.extract(), "cannot rearm extracting state");
    check(g.zone(false), "exit zone");
    check(g.tick(100) && g.snapshot().phase == Phase::Running, "leaving cancels win");
    win(g);
    check(g.snapshot().bank.credits == 120, "banked correct value");
    check(g.snapshot().carried == std::array<int,4>{}, "cleared carried");
    check(!g.extract() && g.tick(60) && g.snapshot().bank.credits == 120, "bank once");
    check(g.buy_upgrade(), "affordable upgrade");
    check(!g.buy_upgrade() && g.snapshot().bank.credits == 20, "spend upgrade once");
    Bank saved = g.snapshot().bank;
    Rules restored;
    check(restored.load(saved), "load persistent bank");
    check(restored.start() && restored.snapshot().max_health == 120, "upgrade applies to next run");
    check(restored.pickup(Item::Salt, 1, 1), "new run pickup identity reusable");
    check(!restored.load(saved), "no mid-run save rollback");
    check(restored.damage(1000), "lethal damage");
    check(restored.snapshot().phase == Phase::Dead && restored.snapshot().carried[2] == 0, "death loses loot");
    check(restored.snapshot().bank.credits == 20 && restored.snapshot().bank.items[3] == 1, "death preserves bank");
    check(!restored.damage(1) && !restored.act(Action::Heal), "dead cannot act");
    check(restored.start() && restored.snapshot().health == 120, "restart after death");
    check(restored.act(Action::Dodge), "dodge accepted");
    check(!restored.damage(10), "dodge invulnerability");
    check(!restored.act(Action::Heavy), "no overlapping actions");
    check(restored.tick(0.31) && restored.damage(10), "invulnerability expires before recovery");
    check(restored.tick(1) && restored.act(Action::Heal), "heal starts");
    check(restored.snapshot().health == 110, "heal has windup");
    check(restored.tick(0.8) && restored.snapshot().health == 120, "heal clamped at cap");
    check(!restored.act(Action::Heal), "full health rejects heal without charge");
    check(restored.snapshot().heals == 1, "charge spent exactly once");
    const double health = restored.snapshot().health;
    check(!restored.damage(-1) && !restored.damage(std::numeric_limits<double>::infinity()), "invalid damage rejected");
    check(!restored.tick(-1) && !restored.tick(std::numeric_limits<double>::quiet_NaN()), "invalid clock rejected");
    check(restored.snapshot().health == health, "invalid requests do not mutate health");
    check(restored.act(Action::Heavy), "heavy accepted");
    check(restored.tick(0.9) && restored.act(Action::Light), "heavy recovery opens light");
    check(restored.damage(1000), "death cancels attack");
    check(restored.snapshot().action == Action::None, "no lingering attack on death");
    saved.version = 9;
    check(!restored.load(saved), "unknown save version rejected");
    saved.version = 1; saved.credits = -1;
    check(!restored.load(saved), "negative bank rejected");
    saved.credits = 0; saved.items[0] = Rules::MaxCount + 1;
    check(!restored.load(saved), "oversized bank rejected");
    check(restored.snapshot().bank.credits == 20, "invalid save preserves current bank");
    Rules capped;
    Bank cap; cap.credits = Rules::MaxCredits;
    check(capped.load(cap) && capped.start(), "credit cap fixture");
    check(!capped.pickup(Item::Iron, 1, 1), "prevent bank overflow before pickup");
    Rules no_regen;
    Tuning tune; tune.stamina_regen = 0;
    check(no_regen.configure(tune) && no_regen.start(), "custom tuning");
    for (int i=0;i<3;++i) check(no_regen.act(Action::Heavy) && no_regen.tick(1), "heavy drains stamina");
    check(!no_regen.act(Action::Heavy), "insufficient stamina");
    Rules charges;
    Tuning three; three.heal_charges = 3;
    check(charges.configure(three) && charges.start() && charges.snapshot().heals == 3, "configurable heal charges");
    check(charges.damage(50) && charges.act(Action::Heal) && charges.tick(0.8) && charges.snapshot().heals == 2, "first charge spent");
    check(charges.damage(50) && charges.act(Action::Heal) && charges.tick(0.8) && charges.snapshot().heals == 1, "second charge spent");
    check(charges.damage(50) && charges.act(Action::Heal) && charges.tick(0.8) && charges.snapshot().heals == 0, "third charge spent");
    check(!charges.act(Action::Heal), "tuned charges exhausted");
    check(charges.damage(1000) && charges.snapshot().phase == Phase::Dead, "end tuned-charge run");
    check(charges.start() && charges.snapshot().heals == 3, "restart restores tuned charges");
    three.heal_charges = -1;
    Rules charges_reject;
    check(!charges_reject.configure(three) && charges_reject.snapshot().heals == 2, "negative charges rejected atomically");
    three.heal_charges = Rules::MaxHeals + 1;
    check(!charges_reject.configure(three), "oversized charges rejected");
    tune.health = std::numeric_limits<double>::quiet_NaN();
    Rules invalid;
    check(!invalid.configure(tune) && invalid.snapshot().health == 100, "bad config rejected atomically");
    Rules before, after;
    check(before.start() && after.start(), "time comparison setup");
    check(before.damage(50) && after.damage(50), "time comparison damage");
    check(before.act(Action::Heal) && after.act(Action::Heal), "time comparison heal");
    check(before.tick(1), "single tick");
    for(int i=0;i<10;++i) check(after.tick(0.1), "partition tick");
    check(before.snapshot().health == after.snapshot().health && before.snapshot().action == after.snapshot().action, "partitioned time same outcome");
    Rules fatal;
    check(fatal.start() && fatal.pickup(Item::Blackbell,1,1) && fatal.zone(true) && fatal.extract(), "death during extraction setup");
    check(fatal.tick(19) && fatal.damage(1000) && fatal.tick(10), "death before timer");
    check(fatal.snapshot().phase == Phase::Dead && fatal.snapshot().bank.credits == 0, "dead cannot extract later");
    std::cout << "PASS: " << checks << " checks\n";
}
